package org.woen.enumerators



enum class RequestResult
{
    ROGER_STARTING_SORTING,
    ROGER_STARTING_SHOOTING,

    FAIL_IS_EMPTY,

    FAIL_AWAITING_SORTING,
    FAIL_ILLEGAL_ARGUMENT,
    FAIL_COLORS_NOT_PRESENT,

    SORTING_FAILED_NOT_SHOOTING,
    FAIL_IGNORE_DUPLICATE_COMMAND
}